# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNFLAnimatedImage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RNFLAnimatedImage
  pod 'FLAnimatedImage', :git => 'https://github.com/Flipboard/FLAnimatedImage'
end
